We-code/Controllers/EmployesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using We_code.Models;

namespace We_code.Controllers
{
    public class EmployesController : Controller
    {
        private data1Entities1 db = new data1Entities1();

        // GET: Employes
        public ActionResult Index()
        {
            return View(db.Employes.ToList());
        }

        // GET: Employes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = db.Employes.Find(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            return View(employe);
        }

        // GET: Employes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employes/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeID,LastName,FirstName,DateBirth")] Employe employe)
        {
            if (ModelState.IsValid)
            {
                db.Employes.Add(employe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employe);
        }

        // GET: Employes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = db.Employes.Find(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            return View(employe);
        }

        // POST: Employes/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeID,LastName,FirstName,DateBirth")] Employe employe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employe);
        }

        // GET: Employes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = db.Employes.Find(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            return View(employe);
        }

        // POST: Employes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employe employe = db.Employes.Find(id);
            db.Employes.Remove(employe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

We-code/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace We_code.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

We-code/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

We-code/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

We-code/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="jumbotron" style="background-color: #E8F9FD;">
    <h1 style="color: #06283D;">WE CODE</h1>
    <p class="lead">WE CODE c'est une ecole qui vous encadrez dans le developpement web . Vous offre des formations dans le Front web (HTML - JS/TY - CSS - BOOTSTRAP) et dans le Backednd web ( ASP.NET - JEE)....'</p>
    <button class="btn btn-default">@Html.ActionLink("Inscription Employeur", "Index", "Employes")</button>
</div>
<h1 class="text-center " style="color: #06283D; ">Front Web</h1>
<div class="row">
    <div class="col-md-4">
        <div class="col text-center"><h2 style="color: #1363DF; ">Html Css</h2>            <img src="~/logo/html.jpg" class="img-rounded " style="width:120px;" /></div>
        <p>
            Vous êtes au bon endroit ! Ce cours est LE cours à suivre si vous débutez complètement en programmation.
            Vous allez vous initier à la programmation avec des langages accessibles, faciles à apprendre, et incontournables du Web : HTML5 et CSS3..
        </p>
    </div>
    <div class="col-md-4">
        <div class="col text-center "><h2 style="color: #1363DF; ">JS / TS</h2>            <img src="~/logo/jsts.png" class="img-rounded " style="width:110px;" /></div>
        <p>
            Vous êtes au bon endroit ! Ce cours est LE cours à suivre si vous débutez complètement en programmation.
            Vous allez apprendre les languages de front web JavaScript et TypeScript et la diffrénce entre ces derniers : JS et TS..<br /><br />
        </p>
    </div>
    <div class="col-md-4">
        <div class="col text-center "><h2 style="color: #1363DF; ">Bootstrap</h2>            <img src="~/logo/bootstrap.png" class="img-rounded " style="width:55px;" /></div>
        <p>
            Vous êtes au bon endroit ! Ce cours est LE cours à suivre si vous débutez complètement en programmation.
            Vous allez apprendre Le framework Bootstrap est un framework CSS. La connaissance du CSS est donc un prérequis indispensable à l’utilisation de ce framework..
        </p>
    </div>
</div>
<h1 class="text-center " style="color: #06283D; "> Back Web</h1>
<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-4">
        <div class="col text-center "><h2 style="color: #1363DF;">Asp.Net</h2>            <img src="~/logo/asp.png" class="img-rounded " style="width:70px;" /></div>
        <p>
            Vous êtes au bon endroit ! Ce cours est LE cours à suivre si vous débutez complètement en programmation.
            Vous allez apprendre ASP.NET est une infrastructure web gratuite permettant de créer de grands sites web et applications web à l’aide de HTML, CSS et JavaScript..<br /><br />
        </p>
    </div>
    <div class="col-md-5">
        <div class="col text-center "><h2 style="color: #1363DF;">JEE</h2>            <img src="~/logo/jee.png" class="img-rounded " style="width:70px;" /></div>
        <p>
            Vous êtes au bon endroit ! Ce cours est LE cours à suivre si vous débutez complètement en programmation.
            Vous allez apprendre Le framework EE (Java Entreprise Edition) est la version entreprise de la plate-forme "Java" qui se compose de l'environnement "JSE" ainsi que de nombreuses API et composant destiné à une utilisation "côté serveur"..
        </p>
    </div>
</div>